#ifndef CLUAGAMEMODE_H
#define CLUAGAMEMODE_H
#include "CLuaClass.h"
#include <string>

class CLuaGamemode
{
public:
	CLuaGamemode();
	~CLuaGamemode();
	void LoadGamemode( const std::string& gamemode, bool reload = false );
	void ReloadGamemode();
	bool IsValidGamemode( const std::string& gamemode );
	void SetGamemode( const std::string& gamemode, bool unknown );
	bool Call( const char* hook );
	void DeriveGamemode( const std::string& gamemode );
	bool Call( int hook );
	bool CallWithArgs( const char* hook );
	bool CallWithArgs( int hook );
	void CallFinish( int hook );
	void CallReturns( int hook, int returns );
	void LoadCurrentlyActiveGamemode();

protected:
	CLuaObject* m_pGamemode;
};

// Definitions
#define LUA_HOOK_AcceptInput 0
#define LUA_HOOK_AdjustMouseSensitivity 1
#define LUA_HOOK_AllowPlayerPickup 2
#define LUA_HOOK_CalcMainActivity 3
#define LUA_HOOK_CalcView 4
#define LUA_HOOK_CalcViewModelView 5
#define LUA_HOOK_CanExitVehicle 6
#define LUA_HOOK_CanPlayerEnterVehicle 7
#define LUA_HOOK_CanPlayerSuicide 8
#define LUA_HOOK_ChatText 9
#define LUA_HOOK_ChatTextChanged 10
#define LUA_HOOK_CheckPassword 11
#define LUA_HOOK_ClientSignOnStateChanged 12
#define LUA_HOOK_CreateClientsideRagdoll 13
#define LUA_HOOK_CreateEntityRagdoll 14
#define LUA_HOOK_CreateMove 15
#define LUA_HOOK_DoAnimationEvent 16
#define LUA_HOOK_DoPlayerDeath 17
#define LUA_HOOK_DrawMonitors 18
#define LUA_HOOK_DrawPhysgunBeam 19
#define LUA_HOOK_EndEntityDriving 20
#define LUA_HOOK_EntityEmitSound 21
#define LUA_HOOK_EntityFireBullets 22
#define LUA_HOOK_PostEntityFireBullets 23
#define LUA_HOOK_EntityKeyValue 24
#define LUA_HOOK_EntityNetworkedVarChanged 25
#define LUA_HOOK_EntityRemoved 26
#define LUA_HOOK_EntityTakeDamage 27
#define LUA_HOOK_PostEntityTakeDamage 28
#define LUA_HOOK_FindUseEntity 29
#define LUA_HOOK_FinishChat 30
#define LUA_HOOK_FinishMove 31
#define LUA_HOOK_GUIMouseDoublePressed 32
#define LUA_HOOK_GUIMousePressed 33
#define LUA_HOOK_GUIMouseReleased 34
#define LUA_HOOK_GetFallDamage 35
#define LUA_HOOK_GetGameDescription 36
#define LUA_HOOK_GetMotionBlurValues 37
#define LUA_HOOK_GetPreferredCarryAngles 38
#define LUA_HOOK_GetTeamColor 39
#define LUA_HOOK_GravGunOnDropped 40
#define LUA_HOOK_GravGunOnPickedUp 41
#define LUA_HOOK_GravGunPickupAllowed 42
#define LUA_HOOK_GravGunPunt 43
#define LUA_HOOK_HUDAmmoPickedUp 44
#define LUA_HOOK_HUDDrawScoreBoard 45
#define LUA_HOOK_HUDItemPickedUp 46
#define LUA_HOOK_HUDPaint 47
#define LUA_HOOK_HUDPaintBackground 48
#define LUA_HOOK_HUDShouldDraw 49
#define LUA_HOOK_HUDWeaponPickedUp 50
#define LUA_HOOK_InitPostEntity 51
#define LUA_HOOK_InputMouseApply 52
#define LUA_HOOK_KeyPress 53
#define LUA_HOOK_KeyRelease 54
#define LUA_HOOK_Move 55
#define LUA_HOOK_NeedsDepthPass 56
#define LUA_HOOK_NetworkEntityCreated 57
#define LUA_HOOK_NetworkIDValidated 58
#define LUA_HOOK_NotifyShouldTransmit 59
#define LUA_HOOK_OnAchievementAchieved 60
#define LUA_HOOK_OnChatTab 61
#define LUA_HOOK_OnCrazyPhysics 62
#define LUA_HOOK_OnDamagedByExplosion 63
#define LUA_HOOK_OnEntityCreated 64
#define LUA_HOOK_OnEntityWaterLevelChanged 65
#define LUA_HOOK_OnNPCKilled 66
#define LUA_HOOK_OnPhysgunFreeze 67
#define LUA_HOOK_OnPhysgunReload 68
#define LUA_HOOK_OnPlayerChat 69
#define LUA_HOOK_OnPlayerHitGround 70
#define LUA_HOOK_PlayerChangedTeam 71
#define LUA_HOOK_OnViewModelChanged 72
#define LUA_HOOK_PhysgunDrop 73
#define LUA_HOOK_PhysgunPickup 74
#define LUA_HOOK_OnPhysgunPickup 75
#define LUA_HOOK_PlayerAuthed 76
#define LUA_HOOK_PlayerBindPress 77
#define LUA_HOOK_PlayerButtonDown 78
#define LUA_HOOK_PlayerButtonUp 79
#define LUA_HOOK_PlayerCanHearPlayersVoice 80
#define LUA_HOOK_PlayerCanPickupItem 81
#define LUA_HOOK_PlayerCanPickupWeapon 82
#define LUA_HOOK_PlayerCanSeePlayersChat 83
#define LUA_HOOK_PlayerConnect 84
#define LUA_HOOK_PlayerDeath 85
#define LUA_HOOK_PlayerDeathSound 86
#define LUA_HOOK_PlayerDeathThink 87
#define LUA_HOOK_PlayerDroppedWeapon 88
#define LUA_HOOK_PlayerDisconnected 89
#define LUA_HOOK_PlayerDriveAnimate 90
#define LUA_HOOK_PlayerEndVoice 91
#define LUA_HOOK_PlayerEnteredVehicle 92
#define LUA_HOOK_PlayerFootstep 93
#define LUA_HOOK_PlayerHurt 94
#define LUA_HOOK_PlayerInitialSpawn 95
#define LUA_HOOK_PlayerLeaveVehicle 96
#define LUA_HOOK_PlayerNoClip 97
#define LUA_HOOK_PlayerPostThink 98
#define LUA_HOOK_PlayerSay 99
#define LUA_HOOK_PlayerSelectSpawn 100
#define LUA_HOOK_PlayerShouldTakeDamage 101
#define LUA_HOOK_PlayerShouldTaunt 102
#define LUA_HOOK_PlayerSilentDeath 103
#define LUA_HOOK_PlayerSpawn 104
#define LUA_HOOK_PlayerSpray 105
#define LUA_HOOK_PlayerStartTaunt 106
#define LUA_HOOK_PlayerStartVoice 107
#define LUA_HOOK_PlayerStepSoundTime 108
#define LUA_HOOK_PlayerSwitchFlashlight 109
#define LUA_HOOK_PlayerSwitchWeapon 110
#define LUA_HOOK_PlayerTick 111
#define LUA_HOOK_PlayerTraceAttack 112
#define LUA_HOOK_PlayerUse 113
#define LUA_HOOK_PostCleanupMap 114
#define LUA_HOOK_PostDraw2DSkyBox 115
#define LUA_HOOK_PostDrawEffects 116
#define LUA_HOOK_PostDrawHUD 117
#define LUA_HOOK_PostDrawOpaqueRenderables 118
#define LUA_HOOK_PostDrawSkyBox 119
#define LUA_HOOK_PostDrawTranslucentRenderables 120
#define LUA_HOOK_PostDrawViewModel 121
#define LUA_HOOK_PostPlayerDeath 122
#define LUA_HOOK_PostPlayerDraw 123
#define LUA_HOOK_PostRender 124
#define LUA_HOOK_PostRenderVGUI 125
#define LUA_HOOK_PreCleanupMap 126
#define LUA_HOOK_PreDrawEffects 127
#define LUA_HOOK_PreDrawHUD 128
#define LUA_HOOK_PreDrawOpaqueRenderables 129
#define LUA_HOOK_PreDrawSkyBox 130
#define LUA_HOOK_PreDrawTranslucentRenderables 131
#define LUA_HOOK_PreDrawViewModel 132
#define LUA_HOOK_PreDrawViewModels 133
#define LUA_HOOK_PrePlayerDraw 134
#define LUA_HOOK_PreRender 135
#define LUA_HOOK_PreventScreenClicks 136
#define LUA_HOOK_PropBreak 137
#define LUA_HOOK_RenderScene 138
#define LUA_HOOK_RenderScreenspaceEffects 139
#define LUA_HOOK_Restored 140
#define LUA_HOOK_Saved 141
#define LUA_HOOK_ScaleNPCDamage 142
#define LUA_HOOK_ScalePlayerDamage 143
#define LUA_HOOK_ScoreboardHide 144
#define LUA_HOOK_ScoreboardShow 145
#define LUA_HOOK_SetupMove 146
#define LUA_HOOK_SetupPlayerVisibility 147
#define LUA_HOOK_SetupSkyboxFog 148
#define LUA_HOOK_SetupWorldFog 149
#define LUA_HOOK_ShouldCollide 150
#define LUA_HOOK_ShouldDrawLocalPlayer 151
#define LUA_HOOK_ShouldDrawParticles 152
#define LUA_HOOK_ShowHelp 153
#define LUA_HOOK_ShowSpare1 154
#define LUA_HOOK_ShowSpare2 155
#define LUA_HOOK_ShowTeam 156
#define LUA_HOOK_ShutDown 157
#define LUA_HOOK_SpawniconGenerated 158
#define LUA_HOOK_StartChat 159
#define LUA_HOOK_StartCommand 160
#define LUA_HOOK_StartEntityDriving 161
#define LUA_HOOK_Think 162
#define LUA_HOOK_Tick 163
#define LUA_HOOK_TranslateActivity 164
#define LUA_HOOK_UpdateAnimation 165
#define LUA_HOOK_VGUIMousePressAllowed 166
#define LUA_HOOK_VGUIMousePressed 167
#define LUA_HOOK_VehicleMove 168
#define LUA_HOOK_ViewPunch 169
#define LUA_HOOK_WeaponEquip 170
#define LUA_HOOK_PlayerAmmoChanged 171
#define LUA_HOOK_PlayerClassChanged 172
#define LUA_HOOK_PlayerHandleAnimEvent 173
#define LUA_HOOK_PlayerFireAnimationEvent 174
#define LUA_HOOK_OnPlayerPhysicsPickup 175
#define LUA_HOOK_OnPlayerPhysicsDrop 176
#define LUA_HOOK_OnPlayerJump 177
#define LUA_HOOK_OnCloseCaptionEmit 178
#define LUA_HOOK_HandlePlayerArmorReduction 179
#define LUA_HOOK_OnChangeActivity 180
#define LUA_HOOK_BehaveUpdate 181
#define LUA_HOOK_Blocked 182
#define LUA_HOOK_BodyUpdate 183
#define LUA_HOOK_Deploy 184
#define LUA_HOOK_DoImpactEffect 185
#define LUA_HOOK_Draw 186
#define LUA_HOOK_DrawTranslucent 187
#define LUA_HOOK_EndTouch 188
#define LUA_HOOK_Equip 189
#define LUA_HOOK_EquipAmmo 190
#define LUA_HOOK_ExpressionFinished 191
#define LUA_HOOK_FireAnimationEvent 192
#define LUA_HOOK_FreezeMovement 193
#define LUA_HOOK_GetAttackSpread 194
#define LUA_HOOK_GetCapabilities 195
#define LUA_HOOK_GetRelationship 196
#define LUA_HOOK_GetRenderMesh 197
#define LUA_HOOK_HandleAnimEvent 198
#define LUA_HOOK_Holster 199
#define LUA_HOOK_ImpactTrace 200
#define LUA_HOOK_KeyValue 201
#define LUA_HOOK_OnCondition 202
#define LUA_HOOK_OnContact 203
#define LUA_HOOK_OnIgnite 204
#define LUA_HOOK_OnInjured 205
#define LUA_HOOK_OnKilled 206
#define LUA_HOOK_OnTraceAttack 207
#define LUA_HOOK_OnLandOnGround 208
#define LUA_HOOK_OnLeaveGround 209
#define LUA_HOOK_OnNavAreaChanged 210
#define LUA_HOOK_OnOtherKilled 211
#define LUA_HOOK_OnStuck 212
#define LUA_HOOK_OnTakeDamage 213
#define LUA_HOOK_OnUnStuck 214
#define LUA_HOOK_PassesDamageFilter 215
#define LUA_HOOK_PassesFilter 216
#define LUA_HOOK_PassesTriggerFilters 217
#define LUA_HOOK_PhysicsCollide 218
#define LUA_HOOK_PhysicsSimulate 219
#define LUA_HOOK_PhysicsUpdate 220
#define LUA_HOOK_RunEngineTask 221
#define LUA_HOOK_StartEngineSchedule 222
#define LUA_HOOK_StartEngineTask 223
#define LUA_HOOK_StartTouch 224
#define LUA_HOOK_TestCollision 225
#define LUA_HOOK_Touch 226
#define LUA_HOOK_UpdateTransmitState 227
#define LUA_HOOK_Use 228
#define LUA_HOOK_IsJumpLegal 229
#define LUA_HOOK_CalcWeaponProficiency 230
#define LUA_HOOK_GetShadowCastDirection 231
#define LUA_HOOK_OnEntitySight 232
#define LUA_HOOK_OnEntitySightLost 233
#define LUA_HOOK_OnMovementFailed 234
#define LUA_HOOK_OnMovementComplete 235
#define LUA_HOOK_OnActiveWeaponChanged 236
#define LUA_HOOK_RunAI 237
#define LUA_HOOK_OnTaskFailed 238
#define LUA_HOOK_OverrideMove 239
#define LUA_HOOK_OverrideMoveFacing 240
#define LUA_HOOK_TranslateSchedule 241
#define LUA_HOOK_OnStateChange 242
#define LUA_HOOK_CustomAmmoDisplay 243
#define LUA_HOOK_DrawHUD 244
#define LUA_HOOK_DrawHUDBackground 245
#define LUA_HOOK_DrawWorldModel 246
#define LUA_HOOK_DrawWorldModelTranslucent 247
#define LUA_HOOK_DrawWeaponSelection 248
#define LUA_HOOK_DoDrawCrosshair 249
#define LUA_HOOK_ShouldDrawViewModel 250
#define LUA_HOOK_GetTracerOrigin 251
#define LUA_HOOK_OnDrop 252
#define LUA_HOOK_OnRemove 253
#define LUA_HOOK_PrimaryAttack 254
#define LUA_HOOK_SecondaryAttack 255
#define LUA_HOOK_Reload 256
#define LUA_HOOK_RenderScreen 257
#define LUA_HOOK_ViewModelDrawn 258
#define LUA_HOOK_TranslateFOV 259
#define LUA_HOOK_SetWeaponHoldType 260
#define LUA_HOOK_CanBePickedUpByNPCs 261
#define LUA_HOOK_NPCShoot_Primary 262
#define LUA_HOOK_NPCShoot_Secondary 263
#define LUA_HOOK_GetNPCRestTimes 264
#define LUA_HOOK_GetNPCBurstSettings 265
#define LUA_HOOK_GetNPCBulletSpread 266
#define LUA_HOOK_ShouldDropOnDie 267
#define LUA_HOOK_ActionSignal 268
#define LUA_HOOK_AllowInput 269
#define LUA_HOOK_ApplySchemeSettings 270
#define LUA_HOOK_ConsoleMessage 271
#define LUA_HOOK_DoClick 272
#define LUA_HOOK_OnActivate 273
#define LUA_HOOK_OnBeginLoadingDocument 274
#define LUA_HOOK_OnCallback 275
#define LUA_HOOK_OnChangeAddressBar 276
#define LUA_HOOK_OnChangeTargetURL 277
#define LUA_HOOK_OnChangeTitle 278
#define LUA_HOOK_OnChildViewCreated 279
#define LUA_HOOK_OnCursorEntered 280
#define LUA_HOOK_OnCursorExited 281
#define LUA_HOOK_OnCursorMoved 282
#define LUA_HOOK_OnDeactivate 283
#define LUA_HOOK_OnDeletion 284
#define LUA_HOOK_OnDocumentReady 285
#define LUA_HOOK_OnFinishLoadingDocument 286
#define LUA_HOOK_OnFocusChanged 287
#define LUA_HOOK_OnGetFocus 288
#define LUA_HOOK_OnKeyCodePressed 289
#define LUA_HOOK_OnKeyCodeReleased 290
#define LUA_HOOK_OnKeyCodeTyped 291
#define LUA_HOOK_OnLoseFocus 292
#define LUA_HOOK_OnMousePressed 293
#define LUA_HOOK_OnMouseReleased 294
#define LUA_HOOK_OnMouseWheeled 295
#define LUA_HOOK_OnScreenSizeChanged 296
#define LUA_HOOK_OnSizeChanged 297
#define LUA_HOOK_OnTextChanged 298
#define LUA_HOOK_OnTextClicked 299
#define LUA_HOOK_PerformLayout 300
#define LUA_HOOK_ResourceLoaded 301
#define LUA_HOOK_TestHover 302
#define LUA_HOOK_DTVar_ReceiveProxyGL 303
#define LUA_HOOK_Float 304
#define LUA_HOOK_Int 305
#define LUA_HOOK_Bool 306
#define LUA_HOOK_Vector 307
#define LUA_HOOK_Angle 308
#define LUA_HOOK_String 309
#define LUA_HOOK_Entity 310
#endif