#include <string>

class CLuaGamemode
{
public:
	CLuaGamemode();
	~CLuaGamemode();
	void LoadGamemode( const std::string& gamemode, bool reload = false );
	void ReloadGamemode();
	bool IsValidGamemode( const std::string& gamemode );
	void SetGamemode( const std::string& gamemode, bool unknown );
	bool Call( const char* hook );
	void DeriveGamemode( const std::string& gamemode );
	bool Call( int hook );
	bool CallWithArgs( const char* hook );
	bool CallWithArgs( int hook );
	void CallFinish( int hook );
	void CallReturns( int hook, int returns );
	void LoadCurrentlyActiveGamemode();
};

// Definitions
#define LUA_HOOK_AcceptInput 1
#define LUA_HOOK_AdjustMouseSensitivity 2
#define LUA_HOOK_AllowPlayerPickup 3
#define LUA_HOOK_CalcMainActivity 4
#define LUA_HOOK_CalcView 5
#define LUA_HOOK_CalcViewModelView 6
#define LUA_HOOK_CanExitVehicle 7
#define LUA_HOOK_CanPlayerEnterVehicle 8
#define LUA_HOOK_CanPlayerSuicide 9
#define LUA_HOOK_ChatText 10
#define LUA_HOOK_ChatTextChanged 11
#define LUA_HOOK_CheckPassword 12
#define LUA_HOOK_ClientSignOnStateChanged 13
#define LUA_HOOK_CreateClientsideRagdoll 14
#define LUA_HOOK_CreateEntityRagdoll 15
#define LUA_HOOK_CreateMove 16
#define LUA_HOOK_DoAnimationEvent 17
#define LUA_HOOK_DoPlayerDeath 18
#define LUA_HOOK_DrawMonitors 19
#define LUA_HOOK_DrawPhysgunBeam 20
#define LUA_HOOK_EndEntityDriving 21
#define LUA_HOOK_EntityEmitSound 22
#define LUA_HOOK_EntityFireBullets 23
#define LUA_HOOK_PostEntityFireBullets 24
#define LUA_HOOK_EntityKeyValue 25
#define LUA_HOOK_EntityNetworkedVarChanged 26
#define LUA_HOOK_EntityRemoved 27
#define LUA_HOOK_EntityTakeDamage 28
#define LUA_HOOK_PostEntityTakeDamage 29
#define LUA_HOOK_FindUseEntity 30
#define LUA_HOOK_FinishChat 31
#define LUA_HOOK_FinishMove 32
#define LUA_HOOK_GUIMouseDoublePressed 33
#define LUA_HOOK_GUIMousePressed 34
#define LUA_HOOK_GUIMouseReleased 35
#define LUA_HOOK_GetFallDamage 36
#define LUA_HOOK_GetGameDescription 37
#define LUA_HOOK_GetMotionBlurValues 38
#define LUA_HOOK_GetPreferredCarryAngles 39
#define LUA_HOOK_GetTeamColor 40
#define LUA_HOOK_GravGunOnDropped 41
#define LUA_HOOK_GravGunOnPickedUp 42
#define LUA_HOOK_GravGunPickupAllowed 43
#define LUA_HOOK_GravGunPunt 44
#define LUA_HOOK_HUDAmmoPickedUp 45
#define LUA_HOOK_HUDDrawScoreBoard 46
#define LUA_HOOK_HUDItemPickedUp 47
#define LUA_HOOK_HUDPaint 48
#define LUA_HOOK_HUDPaintBackground 49
#define LUA_HOOK_HUDShouldDraw 50
#define LUA_HOOK_HUDWeaponPickedUp 51
#define LUA_HOOK_InitPostEntity 52
#define LUA_HOOK_InputMouseApply 53
#define LUA_HOOK_KeyPress 54
#define LUA_HOOK_KeyRelease 55
#define LUA_HOOK_Move 56
#define LUA_HOOK_NeedsDepthPass 57
#define LUA_HOOK_NetworkEntityCreated 58
#define LUA_HOOK_NetworkIDValidated 59
#define LUA_HOOK_NotifyShouldTransmit 60
#define LUA_HOOK_OnAchievementAchieved 61
#define LUA_HOOK_OnChatTab 62
#define LUA_HOOK_OnCrazyPhysics 63
#define LUA_HOOK_OnDamagedByExplosion 64
#define LUA_HOOK_OnEntityCreated 65
#define LUA_HOOK_OnEntityWaterLevelChanged 66
#define LUA_HOOK_OnNPCKilled 67
#define LUA_HOOK_OnPhysgunFreeze 68
#define LUA_HOOK_OnPhysgunReload 69
#define LUA_HOOK_OnPlayerChat 70
#define LUA_HOOK_OnPlayerHitGround 71
#define LUA_HOOK_PlayerChangedTeam 72
#define LUA_HOOK_OnViewModelChanged 73
#define LUA_HOOK_PhysgunDrop 74
#define LUA_HOOK_PhysgunPickup 75
#define LUA_HOOK_OnPhysgunPickup 76
#define LUA_HOOK_PlayerAuthed 77
#define LUA_HOOK_PlayerBindPress 78
#define LUA_HOOK_PlayerButtonDown 79
#define LUA_HOOK_PlayerButtonUp 80
#define LUA_HOOK_PlayerCanHearPlayersVoice 81
#define LUA_HOOK_PlayerCanPickupItem 82
#define LUA_HOOK_PlayerCanPickupWeapon 83
#define LUA_HOOK_PlayerCanSeePlayersChat 84
#define LUA_HOOK_PlayerConnect 85
#define LUA_HOOK_PlayerDeath 86
#define LUA_HOOK_PlayerDeathSound 87
#define LUA_HOOK_PlayerDeathThink 88
#define LUA_HOOK_PlayerDroppedWeapon 89
#define LUA_HOOK_PlayerDisconnected 90
#define LUA_HOOK_PlayerDriveAnimate 91
#define LUA_HOOK_PlayerEndVoice 92
#define LUA_HOOK_PlayerEnteredVehicle 93
#define LUA_HOOK_PlayerFootstep 94
#define LUA_HOOK_PlayerHurt 95
#define LUA_HOOK_PlayerInitialSpawn 96
#define LUA_HOOK_PlayerLeaveVehicle 97
#define LUA_HOOK_PlayerNoClip 98
#define LUA_HOOK_PlayerPostThink 99
#define LUA_HOOK_PlayerSay 100
#define LUA_HOOK_PlayerSelectSpawn 101
#define LUA_HOOK_PlayerShouldTakeDamage 102
#define LUA_HOOK_PlayerShouldTaunt 103
#define LUA_HOOK_PlayerSilentDeath 104
#define LUA_HOOK_PlayerSpawn 105
#define LUA_HOOK_PlayerSpray 106
#define LUA_HOOK_PlayerStartTaunt 107
#define LUA_HOOK_PlayerStartVoice 108
#define LUA_HOOK_PlayerStepSoundTime 109
#define LUA_HOOK_PlayerSwitchFlashlight 110
#define LUA_HOOK_PlayerSwitchWeapon 111
#define LUA_HOOK_PlayerTick 112
#define LUA_HOOK_PlayerTraceAttack 113
#define LUA_HOOK_PlayerUse 114
#define LUA_HOOK_PostCleanupMap 115
#define LUA_HOOK_PostDraw2DSkyBox 116
#define LUA_HOOK_PostDrawEffects 117
#define LUA_HOOK_PostDrawHUD 118
#define LUA_HOOK_PostDrawOpaqueRenderables 119
#define LUA_HOOK_PostDrawSkyBox 120
#define LUA_HOOK_PostDrawTranslucentRenderables 121
#define LUA_HOOK_PostDrawViewModel 122
#define LUA_HOOK_PostPlayerDeath 123
#define LUA_HOOK_PostPlayerDraw 124
#define LUA_HOOK_PostRender 125
#define LUA_HOOK_PostRenderVGUI 126
#define LUA_HOOK_PreCleanupMap 127
#define LUA_HOOK_PreDrawEffects 128
#define LUA_HOOK_PreDrawHUD 129
#define LUA_HOOK_PreDrawOpaqueRenderables 130
#define LUA_HOOK_PreDrawSkyBox 131
#define LUA_HOOK_PreDrawTranslucentRenderables 132
#define LUA_HOOK_PreDrawViewModel 133
#define LUA_HOOK_PreDrawViewModels 134
#define LUA_HOOK_PrePlayerDraw 135
#define LUA_HOOK_PreRender 136
#define LUA_HOOK_PreventScreenClicks 137
#define LUA_HOOK_PropBreak 138
#define LUA_HOOK_RenderScene 139
#define LUA_HOOK_RenderScreenspaceEffects 140
#define LUA_HOOK_Restored 141
#define LUA_HOOK_Saved 142
#define LUA_HOOK_ScaleNPCDamage 143
#define LUA_HOOK_ScalePlayerDamage 144
#define LUA_HOOK_ScoreboardHide 145
#define LUA_HOOK_ScoreboardShow 146
#define LUA_HOOK_SetupMove 147
#define LUA_HOOK_SetupPlayerVisibility 148
#define LUA_HOOK_SetupSkyboxFog 149
#define LUA_HOOK_SetupWorldFog 150
#define LUA_HOOK_ShouldCollide 151
#define LUA_HOOK_ShouldDrawLocalPlayer 152
#define LUA_HOOK_ShouldDrawParticles 153
#define LUA_HOOK_ShowHelp 154
#define LUA_HOOK_ShowSpare1 155
#define LUA_HOOK_ShowSpare2 156
#define LUA_HOOK_ShowTeam 157
#define LUA_HOOK_ShutDown 158
#define LUA_HOOK_SpawniconGenerated 159
#define LUA_HOOK_StartChat 160
#define LUA_HOOK_StartCommand 161
#define LUA_HOOK_StartEntityDriving 162
#define LUA_HOOK_Think 163
#define LUA_HOOK_Tick 164
#define LUA_HOOK_TranslateActivity 165
#define LUA_HOOK_UpdateAnimation 166
#define LUA_HOOK_VGUIMousePressAllowed 167
#define LUA_HOOK_VGUIMousePressed 168
#define LUA_HOOK_VehicleMove 169
#define LUA_HOOK_ViewPunch 170
#define LUA_HOOK_WeaponEquip 171
#define LUA_HOOK_PlayerAmmoChanged 172
#define LUA_HOOK_PlayerClassChanged 173
#define LUA_HOOK_PlayerHandleAnimEvent 174
#define LUA_HOOK_PlayerFireAnimationEvent 175
#define LUA_HOOK_OnPlayerPhysicsPickup 176
#define LUA_HOOK_OnPlayerPhysicsDrop 177
#define LUA_HOOK_OnPlayerJump 178
#define LUA_HOOK_OnCloseCaptionEmit 179
#define LUA_HOOK_HandlePlayerArmorReduction 180
#define LUA_HOOK_OnChangeActivity 181
#define LUA_HOOK_BehaveUpdate 182
#define LUA_HOOK_Blocked 183
#define LUA_HOOK_BodyUpdate 184
#define LUA_HOOK_Deploy 185
#define LUA_HOOK_DoImpactEffect 186
#define LUA_HOOK_Draw 187
#define LUA_HOOK_DrawTranslucent 188
#define LUA_HOOK_EndTouch 189
#define LUA_HOOK_Equip 190
#define LUA_HOOK_EquipAmmo 191
#define LUA_HOOK_ExpressionFinished 192
#define LUA_HOOK_FireAnimationEvent 193
#define LUA_HOOK_FreezeMovement 194
#define LUA_HOOK_GetAttackSpread 195
#define LUA_HOOK_GetCapabilities 196
#define LUA_HOOK_GetRelationship 197
#define LUA_HOOK_GetRenderMesh 198
#define LUA_HOOK_HandleAnimEvent 199
#define LUA_HOOK_Holster 200
#define LUA_HOOK_ImpactTrace 201
#define LUA_HOOK_KeyValue 202
#define LUA_HOOK_OnCondition 203
#define LUA_HOOK_OnContact 204
#define LUA_HOOK_OnIgnite 205
#define LUA_HOOK_OnInjured 206
#define LUA_HOOK_OnKilled 207
#define LUA_HOOK_OnTraceAttack 208
#define LUA_HOOK_OnLandOnGround 209
#define LUA_HOOK_OnLeaveGround 210
#define LUA_HOOK_OnNavAreaChanged 211
#define LUA_HOOK_OnOtherKilled 212
#define LUA_HOOK_OnStuck 213
#define LUA_HOOK_OnTakeDamage 214
#define LUA_HOOK_OnUnStuck 215
#define LUA_HOOK_PassesDamageFilter 216
#define LUA_HOOK_PassesFilter 217
#define LUA_HOOK_PassesTriggerFilters 218
#define LUA_HOOK_PhysicsCollide 219
#define LUA_HOOK_PhysicsSimulate 220
#define LUA_HOOK_PhysicsUpdate 221
#define LUA_HOOK_RunEngineTask 222
#define LUA_HOOK_StartEngineSchedule 223
#define LUA_HOOK_StartEngineTask 224
#define LUA_HOOK_StartTouch 225
#define LUA_HOOK_TestCollision 226
#define LUA_HOOK_Touch 227
#define LUA_HOOK_UpdateTransmitState 228
#define LUA_HOOK_Use 229
#define LUA_HOOK_IsJumpLegal 230
#define LUA_HOOK_CalcWeaponProficiency 231
#define LUA_HOOK_GetShadowCastDirection 232
#define LUA_HOOK_OnEntitySight 233
#define LUA_HOOK_OnEntitySightLost 234
#define LUA_HOOK_OnMovementFailed 235
#define LUA_HOOK_OnMovementComplete 236
#define LUA_HOOK_OnActiveWeaponChanged 237
#define LUA_HOOK_RunAI 238
#define LUA_HOOK_OnTaskFailed 239
#define LUA_HOOK_OverrideMove 240
#define LUA_HOOK_OverrideMoveFacing 241
#define LUA_HOOK_TranslateSchedule 242
#define LUA_HOOK_OnStateChange 243
#define LUA_HOOK_CustomAmmoDisplay 244
#define LUA_HOOK_DrawHUD 245
#define LUA_HOOK_DrawHUDBackground 246
#define LUA_HOOK_DrawWorldModel 247
#define LUA_HOOK_DrawWorldModelTranslucent 248
#define LUA_HOOK_DrawWeaponSelection 249
#define LUA_HOOK_DoDrawCrosshair 250
#define LUA_HOOK_ShouldDrawViewModel 251
#define LUA_HOOK_GetTracerOrigin 252
#define LUA_HOOK_OnDrop 253
#define LUA_HOOK_OnRemove 254
#define LUA_HOOK_PrimaryAttack 255
#define LUA_HOOK_SecondaryAttack 256
#define LUA_HOOK_Reload 257
#define LUA_HOOK_RenderScreen 258
#define LUA_HOOK_ViewModelDrawn 259
#define LUA_HOOK_TranslateFOV 260
#define LUA_HOOK_SetWeaponHoldType 261
#define LUA_HOOK_CanBePickedUpByNPCs 262
#define LUA_HOOK_NPCShoot_Primary 263
#define LUA_HOOK_NPCShoot_Secondary 264
#define LUA_HOOK_GetNPCRestTimes 265
#define LUA_HOOK_GetNPCBurstSettings 266
#define LUA_HOOK_GetNPCBulletSpread 267
#define LUA_HOOK_ShouldDropOnDie 268
#define LUA_HOOK_ActionSignal 269
#define LUA_HOOK_AllowInput 270
#define LUA_HOOK_ApplySchemeSettings 271
#define LUA_HOOK_ConsoleMessage 272
#define LUA_HOOK_DoClick 273
#define LUA_HOOK_OnActivate 274
#define LUA_HOOK_OnBeginLoadingDocument 275
#define LUA_HOOK_OnCallback 276
#define LUA_HOOK_OnChangeAddressBar 277
#define LUA_HOOK_OnChangeTargetURL 278
#define LUA_HOOK_OnChangeTitle 279
#define LUA_HOOK_OnChildViewCreated 280
#define LUA_HOOK_OnCursorEntered 281
#define LUA_HOOK_OnCursorExited 282
#define LUA_HOOK_OnCursorMoved 283
#define LUA_HOOK_OnDeactivate 284
#define LUA_HOOK_OnDeletion 285
#define LUA_HOOK_OnDocumentReady 286
#define LUA_HOOK_OnFinishLoadingDocument 287
#define LUA_HOOK_OnFocusChanged 288
#define LUA_HOOK_OnGetFocus 289
#define LUA_HOOK_OnKeyCodePressed 290
#define LUA_HOOK_OnKeyCodeReleased 291
#define LUA_HOOK_OnKeyCodeTyped 292
#define LUA_HOOK_OnLoseFocus 293
#define LUA_HOOK_OnMousePressed 294
#define LUA_HOOK_OnMouseReleased 295
#define LUA_HOOK_OnMouseWheeled 296
#define LUA_HOOK_OnScreenSizeChanged 297
#define LUA_HOOK_OnSizeChanged 298
#define LUA_HOOK_OnTextChanged 299
#define LUA_HOOK_OnTextClicked 300
#define LUA_HOOK_PerformLayout 301
#define LUA_HOOK_ResourceLoaded 302
#define LUA_HOOK_TestHover 303
#define LUA_HOOK_DTVar_ReceiveProxyGL 304
#define LUA_HOOK_Float 305
#define LUA_HOOK_Int 306
#define LUA_HOOK_Bool 307
#define LUA_HOOK_Vector 308
#define LUA_HOOK_Angle 309
#define LUA_HOOK_String 310
#define LUA_HOOK_Entity 311